#install:
#  - sudo pip install requests
#language: php
#php:
#  - 5.5
#script: phpunit Test.php


sudo: required

services:
  - docker


before_install:
- docker pull juanmafc/appserver
- docker run -i -t -p 8000:8000 juanmafc/appserver /bin/sh; cd /home/taller2-appserver/Appserver/; git pull

script:
- git pull
