sudo: required
dist: trusty

python:
  - "3.4"

install:
#   - sudo pip install --upgrade pip
   - sudo pip install requests[security] 
#  - pip install 'requests[security]'
#  - sudo pip install 'requests[security]'
#   - sudo -H pip install 'requests[security]'

language: c++
#php:
#  - 5.5 
#script: phpunit Test.php
